server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: huangxiangyi
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
#  mapper-locations: classpath*:/mybatis/mapper/*.xml
#  type-aliases-package: com.hxy.domain
#  config-location: classpath:mybatis-config.xml

#mybatis:
#  mapper-locations: classpath*:/mybatis/mapper/*.xml
#  type-aliases-package: com.duing.model

#spring.datasour ce.driver- c las s -name=com.my sql.jdbc .Driver