#server:
#  port: 8080

#使用对象形式赋值
food:
  rice: rice

jasypt:
  encryptor:
    password: 123456

info:
  username:
    ENC(jr1Ru2dxhYoTq2+cOWxhCA==)
  password:
    ENC(Yl2ya6tx7cuSsZ+Otzf5hw==)


student:
  name: 张三
  age: 19
  #使用数组赋值
  color:
    - red
    - green
    - blue
    - yellow

#三个-表示开启一个新的文档的开始
---

